name: RegistrationApp
on:
  push:
    branches: [main]
jobs:
  build:
    runs_on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          [14.18.1]
    steps:
    - uses: actions/checkout@v2
      # checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - name: RegistrationApp ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      # downloads and caches distribution of the requested node.js version
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

