name: RegistrationApp
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          [14.18.1]
    steps:
    - uses: actions/checkout@v2
      # checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: RegistrationApp ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      # downloads and caches distribution of the requested node.js version
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: build docker image
      run: docker build . --file Dockerfile --tag rohityawalkar04/Registration-app:$(git rev-parse --short HEAD)

    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/registration-app

